/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customerserviceticketingsystemswing;

/**
 *
 * @author Adimn
 */
public class UserGuidePanel extends javax.swing.JPanel {

    /**
     * Creates new form UserGuidePanel
     */
    public UserGuidePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 51, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("User Guide for Customer Service Ticketing System");

        jTextArea1.setBackground(new java.awt.Color(204, 204, 255));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("1. Getting Started  \n1.1 System Requirements  \n- Operating System: Windows, macOS, Linux  \n- Java Runtime Environment (JRE) 8 or later  \n- NetBeans IDE (if modifying the source code)  \n- Minimum 4GB RAM for smooth operation  \n\n2. Opening the Application  \n1. Locate the project folder and locate the main class file.  \n2. Double-click it and run to launch the system.  \n\n3. Creating a New Ticket  \n1. Click on the \"New Ticket\" button.  \n2. Fill in the required details:  \n   - Customer Name  \n   - Email Address  \n   - Issue Type (Dropdown Selection)  \n   - Priority Level (High, Medium, Low)  \n   - Description of Issue  \n3. Select a Due Date using the Date Picker.  \n4. Click \"Submit\" to create the ticket.  \n\n4. Viewing Tickets  \n- Go to the \"Ticket List\" section.  \n- Use the Search Bar to find specific tickets by ID or Customer Name.  \n- Click on a ticket to view its details.  \n\n5. Common Questions  \n5.1 Do I Need an Account?  \n- No. You can create and view tickets without logging in.  \n\n5.2 Can I Edit or Delete a Ticket?  \n- No. Once a ticket is created, it cannot be changed or removed.  \n\n5.3 The App Isn’t Opening. What Do I Do?  \n- Make sure Java is installed.  \n- Restart your computer and try again.  \n- If the problem continues, contact support.  \n\n6. Troubleshooting & Support  \n6.1 Application Not Opening?  \n- Ensure Java is installed.  \n- Check if your system meets the requirements.  \n- Restart the application.  \n\n6.2 Need Further Assistance?  \n- Contact IT Support at support@company.com.  \n");
        jTextArea1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTextArea1.setCaretColor(new java.awt.Color(0, 153, 255));
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
