/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package customerserviceticketingsystemswing;
import customerserviceticketingsystemswing.DAO.CustomerManager;
import customerserviceticketingsystemswing.DAO.Customer;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import java.awt.GridLayout;
import java.util.List;
import javax.swing.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTextField;
import javax.swing.JButton;
import javax.swing.JLabel;


/**
 *
 * @author Adimn
 */
public class ViewCustomerListPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewCustomerListPanel
     */
    public ViewCustomerListPanel() {
        initComponents();
        refreshCustomerTable();

        // Action listener for Delete button
        jButton1.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int selectedRow = customerTable.getSelectedRow();
                if (selectedRow >= 0) {
                    String customerId = (String) customerTable.getValueAt(selectedRow, 0);
                    CustomerManager.getInstance().deleteCustomer(customerId);
                    refreshCustomerTable();
                } else {
                    JOptionPane.showMessageDialog(ViewCustomerListPanel.this, "No customer selected for deletion.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });

        // Action listener for Edit button
        jButton3.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                int selectedRow = customerTable.getSelectedRow();
                if (selectedRow >= 0) {
                    String customerId = (String) customerTable.getValueAt(selectedRow, 0);
                    Customer customer = CustomerManager.getInstance().getCustomerById(customerId);
                    if (customer != null) {
                        new EditCustomerDialog(customer).setVisible(true);
                        refreshCustomerTable();
                    }
                } else {
                    JOptionPane.showMessageDialog(ViewCustomerListPanel.this, "No customer selected for editing.", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        });
    }

    private void refreshCustomerTable() {
        List<Customer> customers = CustomerManager.getInstance().getAllCustomers();
        DefaultTableModel model = (DefaultTableModel) customerTable.getModel();
        model.setRowCount(0);
        for (Customer customer : customers) {
            model.addRow(new Object[]{customer.getId(), customer.getName(), customer.getPhone(), customer.getEmail()});
        }
    }

    private class EditCustomerDialog extends JDialog {
        private Customer customer;
        private JTextField nameField;
        private JTextField emailField;
        private JTextField phoneField;

        public EditCustomerDialog(Customer customer) {
            this.customer = customer;
            initComponents();
            setTitle("Edit Customer");
            setModal(true);
            setSize(300, 300);
            setLocationRelativeTo(null);
            setVisible(true);
        }

        private void initComponents() {
            nameField = new JTextField(customer.getName());
            emailField = new JTextField(customer.getEmail());
            phoneField = new JTextField(customer.getPhone());
            JButton saveButton = new JButton("Save");
            saveButton.addActionListener(e -> saveChanges());

            // Layout setup
            setLayout(new GridLayout(4, 2));
            add(new JLabel("Name:"));
            add(nameField);
            add(new JLabel("Email:"));
            add(emailField);
            add(new JLabel("Phone:"));
            add(phoneField);
            add(saveButton);
        }

        private void saveChanges() {
            String newName = nameField.getText();
            String newEmail = emailField.getText();
            String newPhone = phoneField.getText();
            CustomerManager.getInstance().editCustomer(customer.getId(), newName, newEmail, newPhone);
            dispose(); // Close the dialog
            refreshCustomerTable(); // Update the table after editing
        }
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        customerTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        customerTable.setBackground(new java.awt.Color(204, 204, 255));
        customerTable.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        customerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Customer Id", "Name", "Phone", "Email"
            }
        ));
        customerTable.setRowHeight(75);
        jScrollPane1.setViewportView(customerTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Customer List");

        jButton1.setBackground(new java.awt.Color(255, 0, 0));
        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton1.setText("Delete");

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton3.setText("Edit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(349, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(339, 339, 339))
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable customerTable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}

